title: 古戳戳
description: 戳一下，探古趣
baseurl: /Antichuo
url: https://relHIGH.github.io
layout: default
cache_bust: 1775560500 # 强制全站缓存更新

defaults:
  - scope:
      path: ""
    values:
      layout: "default"
